<a href="https://colab.research.google.com/github/Julien-Dufresne/data_cleaning_activity_python_pandas/blob/main/Eniac_Project_DF_Review_of_orderlines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Review of orderlines

In [ ]:
import pandas as pd

In [ ]:
#original orderlines
url = "https://drive.google.com/file/d/1FYhN_2AzTBFuWcfHaRuKcuCE6CWXsWtG/view?usp=sharing" # orderlines.csv
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
orderlines_csv = pd.read_csv(path)

In [ ]:
#orderlines_cl
url = "https://drive.google.com/file/d/1NnXO1FX6caFP7d1ctXH6ZA5yezKC4oUr/view?usp=sharing" #orderlines_cl.csv
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
orderliness_cl_csv = pd.read_csv(path)

# No duplicated nor NA values

#Working on oderlines_df

In [ ]:
orderlines_df = orderlines_csv.copy()

In [ ]:
orderlines_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293983 entries, 0 to 293982
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                293983 non-null  int64
 1   id_order          293983 non-null  int64
 2   product_id        293983 non-null  int64
 3   product_quantity  293983 non-null  int64
 4   sku               293983 non-null  object
 5   unit_price        293983 non-null  object
 6   date              293983 non-null  object
dtypes: int64(4), object(3)
memory usage: 15.7+ MB

In [ ]:
orderlines_df.isna().sum()

id                  0
id_order            0
product_id          0
product_quantity    0
sku                 0
unit_price          0
date                0
dtype: int64

In [ ]:
orderlines_df.duplicated().sum()

np.int64(0)

# Remove the point

In [ ]:
#it seems like all the unit price above 1000 have an extra .  after the 1000 denominator.

In [ ]:
orderlines_df[orderlines_df['unit_price'].astype(str).str.count(r'\.') > 1].tail(10)

,id,id_order,product_id,product_quantity,sku,unit_price,date
293728,1649733,527181,0,1,APP2489,1.099.00,2018-03-14 12:17:40
293748,1649776,527201,0,1,APP2489,1.099.00,2018-03-14 12:23:56
293756,1649792,527208,0,1,APP2489,1.099.00,2018-03-14 12:26:04
293790,1649853,527239,0,1,PAC2085,3.475.00,2018-03-14 12:36:46
293838,1649954,527286,0,1,APP2490,1.159.00,2018-03-14 12:55:14
293862,1649999,452946,0,1,APP2075,2.999.00,2018-03-14 13:03:33
293887,1650045,527321,0,1,PAC2148,3.497.00,2018-03-14 13:10:15
293889,1650050,527324,0,1,PAC2117,3.075.00,2018-03-14 13:10:56
293911,1650088,527342,0,1,APP2492,1.329.00,2018-03-14 13:24:51
293936,1650135,527364,0,1,APP2491,1.329.00,2018-03-14 13:36:13

In [ ]:
# removing the thousand denominator's point
orderlines_df['unit_price'] = orderlines_df['unit_price'].astype(str).str.replace(r'\.(?=.*\.)', '', regex=True)
orderlines_df['unit_price']
orderlines_df.sample(10)

,id,id_order,product_id,product_quantity,sku,unit_price,date
164392,1441539,441047,0,1,GTE0105,826.19,2017-11-24 19:35:13
154965,1424998,433362,0,1,APP2349,3489.59,2017-11-23 06:56:13
219261,1528894,478049,0,1,APP2501,386.09,2017-12-31 13:17:31
43357,1209357,337259,0,1,PAC1260,360.99,2017-03-20 23:07:33
201653,1495374,462451,0,1,PAC2145,2911.59,2017-12-13 23:27:19
183744,1471577,453358,0,1,BEL0371,34.99,2017-12-01 18:19:45
150396,1417268,429647,0,1,AP20311,319.00,2017-11-20 22:30:50
73021,1261699,362383,0,1,WAC0132,179.99,2017-06-05 13:13:20
37381,1198163,332133,0,1,APP1919,35.00,2017-03-05 14:52:50
114424,1348104,397909,0,1,WAC0055,22.99,2017-09-08 15:44:09

# Convert Unit_price into numeric and date into date and time

In [ ]:
orderlines_df["date"] = pd.to_datetime(orderlines_df["date"])

In [ ]:
orderlines_df['unit_price'] = pd.to_numeric(orderlines_df['unit_price'])

In [ ]:
orderlines_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293983 entries, 0 to 293982
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                293983 non-null  int64
 1   id_order          293983 non-null  int64
 2   product_id        293983 non-null  int64
 3   product_quantity  293983 non-null  int64
 4   sku               293983 non-null  object
 5   unit_price        293983 non-null  float64
 6   date              293983 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(4), object(1)
memory usage: 15.7+ MB

In [ ]:
orderlines_df.nsmallest(10,'unit_price')

,id,id_order,product_id,product_quantity,sku,unit_price,date
77008,1268645,365886,0,1,APP1465,-119.0,2017-06-15 12:48:54
53515,1227566,345934,0,1,KIN0153-2,0.0,2017-04-13 13:47:21
53530,1227590,345957,0,1,WDT0347,0.0,2017-04-13 14:44:05
56529,1232832,348502,0,1,LIBRO,0.0,2017-04-21 18:14:54
56562,1232888,348531,0,1,LIBRO,0.0,2017-04-21 19:46:54
56576,1232909,348542,0,1,LIBRO,0.0,2017-04-21 20:48:06
56617,1232975,348572,0,1,LIBRO,0.0,2017-04-21 23:45:18
56636,1233009,348590,0,1,LIBRO,0.0,2017-04-22 01:16:41
56641,1233016,348595,0,1,LIBRO,0.0,2017-04-22 01:47:52
56648,1233027,348601,0,2,LIBRO,0.0,2017-04-22 03:02:45

#*skipped **Fixing outliers with negative unit_price

In [ ]:
#remove negative outlier
orderlines_df = orderlines_df.loc[orderlines_df['id'] != 1268645]

In [ ]:
orderlines_df.nlargest(10,'unit_price')

,id,id_order,product_id,product_quantity,sku,unit_price,date
36979,1197439,331780,0,1,NEA0009,159989.83,2017-03-03 22:29:21
38317,1200059,332976,0,6,LAC0223,15349.00,2017-03-07 15:51:14
282442,1632863,520029,0,1,APP2660,14725.00,2018-03-02 11:57:52
232052,1551007,487164,0,1,APP2660,14580.00,2018-01-09 23:33:16
232077,1551059,487192,0,1,APP2660,14580.00,2018-01-10 00:05:59
234834,1555558,488935,0,4,APP2660,14580.00,2018-01-11 21:11:34
241912,1567694,491691,0,1,APP2660,14580.00,2018-01-18 14:40:05
248338,1577659,497375,0,1,APP2660,14580.00,2018-01-23 23:55:41
253465,1585660,500546,0,1,APP2660,14580.00,2018-01-29 01:55:02
255123,1587927,501275,0,1,APP2660,14580.00,2018-01-29 17:18:55

In [ ]:
#remove top outlier : id_order 331780, with unit price of 159989.83

In [ ]:
#remove top outlier : id_order 331780, with unit price of 159989.83
orderlines_df = orderlines_df.loc[orderlines_df['id_order'] != 331780]

In [ ]:
orderlines_df.loc[orderlines_df['id_order'] == 331780]

,id,id_order,product_id,product_quantity,sku,unit_price,date
36979,1197439,331780,0,1,NEA0009,159989.83,2017-03-03 22:29:21

In [ ]:
orderlines_df.nsmallest(10,'unit_price')

,id,id_order,product_id,product_quantity,sku,unit_price,date
53515,1227566,345934,0,1,KIN0153-2,0.0,2017-04-13 13:47:21
53530,1227590,345957,0,1,WDT0347,0.0,2017-04-13 14:44:05
56529,1232832,348502,0,1,LIBRO,0.0,2017-04-21 18:14:54
56562,1232888,348531,0,1,LIBRO,0.0,2017-04-21 19:46:54
56576,1232909,348542,0,1,LIBRO,0.0,2017-04-21 20:48:06
56617,1232975,348572,0,1,LIBRO,0.0,2017-04-21 23:45:18
56636,1233009,348590,0,1,LIBRO,0.0,2017-04-22 01:16:41
56641,1233016,348595,0,1,LIBRO,0.0,2017-04-22 01:47:52
56648,1233027,348601,0,2,LIBRO,0.0,2017-04-22 03:02:45
56665,1233054,348615,0,1,LIBRO,0.0,2017-04-22 09:07:34

In [ ]:
orderlines_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 293981 entries, 0 to 293982
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                293981 non-null  int64
 1   id_order          293981 non-null  int64
 2   product_id        293981 non-null  int64
 3   product_quantity  293981 non-null  int64
 4   sku               293981 non-null  object
 5   unit_price        293981 non-null  float64
 6   date              293981 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(4), object(1)
memory usage: 17.9+ MB

# Fixing 0s

In [ ]:
orderlines_df.loc[(orderlines_df['unit_price'] == 0.0)]

,id,id_order,product_id,product_quantity,sku,unit_price,date
53515,1227566,345934,0,1,KIN0153-2,0.0,2017-04-13 13:47:21
53530,1227590,345957,0,1,WDT0347,0.0,2017-04-13 14:44:05
56529,1232832,348502,0,1,LIBRO,0.0,2017-04-21 18:14:54
56562,1232888,348531,0,1,LIBRO,0.0,2017-04-21 19:46:54
56576,1232909,348542,0,1,LIBRO,0.0,2017-04-21 20:48:06
...,...,...,...,...,...,...,...
291880,1646431,525595,0,1,SYN0150,0.0,2018-03-11 20:50:46
292216,1647014,525883,0,1,APP0699,0.0,2018-03-12 12:26:57
292388,1647334,526025,0,1,WAC0251,0.0,2018-03-12 16:31:39
292905,1648288,526430,0,1,OWC0110,0.0,2018-03-13 13:27:05
292906,1648289,526430,0,1,NTE0013,0.0,2018-03-13 13:27:05

In [ ]:
#removing 0s in orders
updated_orderlines_df = orderlines_df.loc[(orderlines_df['unit_price'] != 0.0)]

In [ ]:
updated_orderlines_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 293116 entries, 0 to 293982
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                293116 non-null  int64
 1   id_order          293116 non-null  int64
 2   product_id        293116 non-null  int64
 3   product_quantity  293116 non-null  int64
 4   sku               293116 non-null  object
 5   unit_price        293116 non-null  float64
 6   date              293116 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(4), object(1)
memory usage: 17.9+ MB

In [ ]:
orderlines_cl= orderlines_df.copy()

# saving changes into new DF and uploading onto the drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
orderlines_cl.to_csv("/content/drive/MyDrive/orderlines_cl.csv", index=False)

In [ ]:
orderlines_cl

,id,id_order,product_id,product_quantity,sku,unit_price,date
0,1119109,299539,0,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,0,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,0,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,0,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,0,1,JBL0104,23.74,2017-01-01 01:06:38
...,...,...,...,...,...,...,...
293978,1650199,527398,0,1,JBL0122,42.99,2018-03-14 13:57:25
293979,1650200,527399,0,1,PAC0653,141.58,2018-03-14 13:57:34
293980,1650201,527400,0,2,APP0698,9.99,2018-03-14 13:57:41
293981,1650202,527388,0,1,BEZ0204,19.99,2018-03-14 13:58:01
293982,1650203,527401,0,1,APP0927,13.99,2018-03-14 13:58:36

In [ ]:
orderlines_df.shape

(293981, 7)

In [ ]:
df.head().size

2057881

In [ ]:
orderlines_df.head()

,id,id_order,product_id,product_quantity,sku,unit_price,date
0,1119109,299539,0,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,0,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,0,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,0,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,0,1,JBL0104,23.74,2017-01-01 01:06:38

In [ ]:
orderlines_df.tail()

,id,id_order,product_id,product_quantity,sku,unit_price,date
293978,1650199,527398,0,1,JBL0122,42.99,2018-03-14 13:57:25
293979,1650200,527399,0,1,PAC0653,141.58,2018-03-14 13:57:34
293980,1650201,527400,0,2,APP0698,9.99,2018-03-14 13:57:41
293981,1650202,527388,0,1,BEZ0204,19.99,2018-03-14 13:58:01
293982,1650203,527401,0,1,APP0927,13.99,2018-03-14 13:58:36

In [ ]:
orderlines_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293983 entries, 0 to 293982
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                293983 non-null  int64
 1   id_order          293983 non-null  int64
 2   product_id        293983 non-null  int64
 3   product_quantity  293983 non-null  int64
 4   sku               293983 non-null  object
 5   unit_price        293983 non-null  object
 6   date              293983 non-null  object
dtypes: int64(4), object(3)
memory usage: 15.7+ MB

In [ ]:
orderlines_df.describe()

                 id       id_order  product_id  product_quantity
count  2.939830e+05  293983.000000    293983.0     293983.000000
mean   1.397918e+06  419999.116544         0.0          1.121126
std    1.530096e+05   66344.486479         0.0          3.396569
min    1.119109e+06  241319.000000         0.0          1.000000
25%    1.262542e+06  362258.500000         0.0          1.000000
50%    1.406940e+06  425956.000000         0.0          1.000000
75%    1.531322e+06  478657.000000         0.0          1.000000
max    1.650203e+06  527401.000000         0.0        999.000000

In [ ]:
orderlines_df.nunique()

id                  293983
id_order            204855
product_id               1
product_quantity        67
sku                   7951
unit_price           11329
date                251631
dtype: int64

In [ ]:
orderlines_df.isna().sum()

id                  0
id_order            0
product_id          0
product_quantity    0
sku                 0
unit_price          0
date                0
dtype: int64

In [ ]:
orderlines_df.duplicated().sum()

np.int64(0)